{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "spring-boot.fullname" . }}
  labels:
    {{- include "spring-boot.labels" . | nindent 4 }}
spec:
{{- if .Values.istio.gateway }}
  gateways:
{{- range .Values.istio.gateway.hosts }}
    - {{ . | quote }}
{{- end }}  
{{- end }}
  hosts:
{{- if .Values.istio.virtualService.hosts }}
{{- range .Values.istio.virtualService.hosts }}
    - "{{ . }}.{{ .Release.Namespace }}.{{ .Values.istio.domain }}"
{{- end }}
{{- else }}
    - "{{ .Values.service.name }}.{{ .Release.Namespace }}.{{ .Values.istio.domain }}"
{{- end }}
  http:
{{- range .Values.istio.virtualService.rules }}
{{- if .match }}
    - match:
{{- if .uriPrefix }}
      - uri:
          prefix: {{ . | quote }}
{{- end }}
{{- end }}
      route:
      - destination:
          host: {{ .routeDestinationHost | quote }}
          {{- if .routeDestinationSubset }}
          subset: {{ .routeDestinationSubset | quote }}
          {{- end }}
{{- end }}
{{- end }}  