# Default values for istio-virtual-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""
# Istio VirtualService specification : https://istio.io/latest/docs/reference/config/networking/virtual-service/
VirtualService:
  hosts:
    - api.exemple.com
  http:
  - name: "api-v1"
    match:
    - uri:
        prefix: "/api/v1"
    route:
    - destination:
        host: api.svc.defaul.local
        subset: v1
  - name: "api-v2"
    route:
    - destination:
        host: api.svc.defaul.local
        subset: v2
# Istio DestinationRule specification : https://istio.io/latest/docs/reference/config/networking/destination-rule/
DestinationRule:
  host: api.svc.defaul.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
