{{- if .Values.VirtualService -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "istio-virtual-service.fullname" . }}
  labels:
    {{- include "istio-virtual-service.labels" . | nindent 4 }}
spec:
{{ .Values.VirtualService | toYaml | indent 2 }}
{{- end }}
 
  